[syntax]
name = "clausewitz"
assignment = "="
comment = "#"

[syntax.tokens]
string_quote = "\""
escape = "\\"

[syntax.whitespace]
newline_significant = false
indent_significant = false

[syntax.children]
children_by = "delimiter"
open = "{"
close = "}"