[syntax]
name = "clausewitz"
assignment = "="
comment = "#"

[syntax.tokens]
string_quotes = ["\""]
escape = "\\"
comparison_operators = ["<", ">", "<=", ">=", "!=", "=="]

[syntax.whitespace]
newline_significant = false

[syntax.children]
children_by = "bracket"
open = "{"
close = "}"